# Generated by Django 4.2.17 on 2024-12-30 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_lead_date_added_lead_desciption_lead_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='desciption',
            new_name='description',
        ),
    ]
